import assert from 'node:assert/strict';
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import { chromium } from '@playwright/test';
import { createAdminServer } from '../src/server.mjs';
import { openStore } from '../src/store.mjs';
import { decrypt, digest, totp } from '../src/crypto.mjs';
import { signedResponse } from '../bin/signer.mjs';

const owner='kavasupport@kavaroutes.com',store=openStore(':memory:');
const config={mode:'local',origin:'',encryptionKey:randomBytes(32)};
store.run("INSERT INTO admins(email,role,state,invite_hash,invite_expiry) VALUES(?,'OWNER','INVITED',?,?)",owner,digest('browser-only-invite'),Date.now()+60000);
const server=createAdminServer({config,store});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));config.origin=`http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(config.origin);await page.getByText('Local test: email ownership').waitFor();
  await page.locator('#challenge-status').filter({hasText:'Ready.'}).waitFor();
  await page.locator('#invite-file').setInputFiles({name:'wrong-account.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({email:'other@example.com',invite:'wrong'}))});
  await page.getByRole('button',{name:'Download sign-in challenge'}).click();
  await page.locator('#challenge-status').filter({hasText:'Enrollment file is for another email.'}).waitFor();
  await page.locator('#invite-file').setInputFiles({name:'enrollment.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({email:owner,invite:'browser-only-invite'}))});
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download sign-in challenge'}).click();
  const challenge=await readFile(await (await download).path(),'utf8');
  const retryDownload=page.waitForEvent('download');await page.locator('#challenge-download').click();
  assert.equal(await readFile(await (await retryDownload).path(),'utf8'),challenge);
  const response=signedResponse(generateKeyPairSync('ml-dsa-65').privateKey,challenge);
  await page.locator('#response-file').setInputFiles({name:'response.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(response))});
  await page.getByRole('button',{name:'Verify signature'}).click();await page.locator('#enroll-panel').waitFor({state:'visible'});
  const pending=store.get('SELECT * FROM enrollments WHERE email=?',owner);
  await page.locator('#enroll-code').fill(totp(decrypt(pending.secret,config.encryptionKey,owner)));
  await page.getByRole('button',{name:'Finish enrollment'}).click();await page.locator('#dashboard').waitFor({state:'visible'});
  for(const [name,contact] of [['North Coast Medical Transport','office@example.com'],['Valley Mobility Services','dispatch@example.com']]){
    await page.getByLabel('Business name',{exact:true}).fill(name);await page.getByLabel('Contact email',{exact:true}).fill(contact);
    await page.getByRole('button',{name:'Save test business'}).click();await page.locator('#business-rows').getByRole('cell',{name,exact:true}).waitFor();
  }
  await page.locator('#business-rows').getByRole('row').filter({hasText:'North Coast Medical Transport'}).getByRole('button',{name:'Edit'}).click();
  await page.getByLabel('Account status').selectOption('ACTIVE');await page.getByLabel('Plan').selectOption('GROWTH');
  await page.getByRole('button',{name:'Save test business'}).click();await page.locator('#business-rows').getByRole('row').filter({hasText:'North Coast Medical Transport'}).getByText('ACTIVE',{exact:true}).waitFor();
  await page.getByRole('searchbox').fill('Valley');assert.equal(await page.locator('#business-rows tr').count(),1);await page.getByRole('searchbox').fill('');
  const subscription=page.locator('#subscription-form');
  await subscription.locator('[name=monthly]').fill('199.00');await subscription.locator('[name=status]').selectOption('ACTIVE');
  await subscription.getByRole('button',{name:'Save subscription record'}).click();await page.locator('#subscription-rows').getByText('$199.00',{exact:true}).waitFor();
  const invoice=page.locator('#invoice-form');
  await invoice.locator('[name=subtotal]').fill('199.00');
  await invoice.getByRole('button',{name:'Create draft invoice'}).click();await page.locator('#invoice-rows').getByText('DRAFT',{exact:true}).waitFor();
  await page.locator('#invoice-rows').getByRole('button',{name:'Issue',exact:true}).click();await page.locator('#invoice-rows').getByText('ISSUED',{exact:true}).waitFor();
  const dialogs=dialog=>dialog.accept(dialog.message().startsWith('Payment date')?new Date().toISOString().slice(0,10):'test-bank-reference');page.on('dialog',dialogs);
  await page.locator('#invoice-rows').getByRole('button',{name:'Record payment'}).click();await page.locator('#invoice-rows').getByText('PAID',{exact:true}).waitFor();page.off('dialog',dialogs);
  const expense=page.locator('#expense-form');await expense.locator('[name=vendor]').fill('Cloud test');await expense.locator('[name=amount]').fill('30.00');await expense.locator('[name=description]').fill('Test hosting');
  await expense.getByRole('button',{name:'Record expense'}).click();await page.locator('#expense-rows').getByText('Cloud test',{exact:true}).waitFor();
  const csv=page.waitForEvent('download');await page.locator('#export-invoices').click();const csvText=await readFile(await (await csv).path(),'utf8');assert.ok(csvText.includes('PAID')&&csvText.includes('199.00'));
  const usage=page.locator('#usage-form');await usage.locator('[name=trips]').fill('550');await usage.locator('[name=routeRequests]').fill('1100');await usage.getByRole('button',{name:'Save monthly usage'}).click();await page.locator('#usage-coverage').filter({hasText:'1 of 2'}).waitFor();
  await page.locator('#use-usage').click();await page.locator('#usage-coverage').filter({hasText:'Applied sample averages'}).waitFor();
  assert.equal(await page.locator('#model-form [name=enterpriseTrips]').inputValue(),'25.00');
  const contact=page.locator('#customer-form');await contact.locator('[name=contactName]').fill('Casey');await contact.locator('[name=phone]').fill('555-0100');await contact.locator('[name=emailEnabled]').check();await contact.getByRole('button',{name:'Save customer contact'}).click();await page.locator('#customer-rows').getByText('Casey',{exact:true}).waitFor();
  const template=page.locator('#template-form');await template.locator('[name=name]').fill('Account reminder');await template.locator('[name=subject]').fill('Hello {{contact_name}}');await template.locator('[name=body]').fill('A reminder for {{business_name}}.');await template.getByRole('button',{name:'Save email template'}).click();await page.locator('#mail-template option').filter({hasText:'Account reminder'}).waitFor({state:'attached'});
  await page.locator('#mail-template').selectOption({label:'Account reminder'});
  await page.locator('#mail-compose').getByRole('button',{name:'Preview email'}).click();await page.locator('#mail-preview').filter({hasText:'Hello Casey'}).waitFor();await page.locator('#queue-mail').click();await page.locator('#mail-rows').getByText('QUEUED',{exact:true}).waitFor();await page.locator('#mail-rows').getByRole('button',{name:'Cancel message'}).click();await page.locator('#mail-rows').getByText('CANCELED',{exact:true}).waitFor();
  const rule=page.locator('#rule-form');await rule.locator('[name=templateId]').selectOption({label:'Account reminder'});await rule.locator('[name=name]').fill('Due day reminder');await rule.getByRole('button',{name:'Save reminder rule'}).click();await page.locator('#rule-list').filter({hasText:'Due day reminder'}).waitFor();
  await invoice.locator('[name=subtotal]').fill('299.00');await invoice.getByRole('button',{name:'Create draft invoice'}).click();await page.locator('#invoice-rows').getByText('DRAFT',{exact:true}).waitFor();await page.locator('#invoice-rows').getByRole('button',{name:'Issue',exact:true}).click();await page.locator('#invoice-rows').getByText('ISSUED',{exact:true}).waitFor();page.on('dialog',dialogs);await page.locator('#invoice-rows').getByRole('button',{name:'Record payment'}).click();await page.locator('#invoice-rows tr').first().getByText('PAID',{exact:true}).waitFor();page.off('dialog',dialogs);await page.locator('#mail-refresh').click();await page.locator('#mail-rows tr').filter({hasText:'Payment received'}).getByText('QUEUED',{exact:true}).waitFor();
  await page.getByLabel('Support email',{exact:true}).fill('support@example.com');
  const invitation=page.waitForEvent('download');await page.getByRole('button',{name:'Create enrollment file'}).click();
  assert.equal(JSON.parse(await readFile(await (await invitation).path(),'utf8')).email,'support@example.com');
  await page.getByText('support@example.com · SUPPORT · INVITED',{exact:true}).waitFor();
  await page.reload();await page.locator('#dashboard').waitFor({state:'visible'});
  assert.equal(await page.locator('#business-rows tr').count(),2);
  await mkdir('.tooling/admin-preview',{recursive:true});
  await page.screenshot({path:'.tooling/admin-preview/dashboard-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'.tooling/admin-preview/dashboard-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.locator('#login').waitFor({state:'visible'});
  assert.deepEqual(errors,[]);
  console.log('ADMIN_BROWSER_SMOKE_PASSED: enrollment, business management, subscription, invoice create/issue/payment, expenses, CSV download, usage-informed planning, customer directory, email templates/preview/schedule/cancel, reminder rules, automatic payment receipt, invitation, reload, mobile, logout');
} finally {await browser?.close();await new Promise(resolve=>server.close(resolve));store.close();}
