import {createPrivateDevelopmentTransport,type DevelopmentFetch} from '@kavaroutes/api-contracts/private-development-transport';
const organization='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',facility='30000000-0000-4000-8000-000000000002',prefix=`/v1/organizations/${organization}/facility`;
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_FACILITY_RESPONSE');return value as Record<string,unknown>;}
export function decodeFacilityTrip(value:unknown){const v=object(value);
 if(Object.keys(v).sort().join()!=='lifecycle,relatedTripReference,scheduledAt'||typeof v.relatedTripReference!=='string'||!uuid.test(v.relatedTripReference)||!['SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW','NEEDS_COORDINATION'].includes(String(v.lifecycle))||typeof v.scheduledAt!=='string'||!Number.isFinite(Date.parse(v.scheduledAt)))throw new Error('INVALID_FACILITY_RESPONSE');
 return {relatedTripReference:v.relatedTripReference,lifecycle:String(v.lifecycle),scheduledAt:v.scheduledAt};
}
export function createCloudFacilityApi(baseUrl:string,fetcher:DevelopmentFetch){const transport=createPrivateDevelopmentTransport({baseUrl,persona:'facility',fetch:fetcher});return{
 async authenticate(signal?:AbortSignal){return transport.request('/v1/me',body=>{const v=object(body);if(v.principalKind!=='SYNTHETIC_USER'||v.principalId!=='10000000-0000-4000-8000-000000000003'||!Array.isArray(v.organizations))throw new Error('INVALID_FACILITY_SESSION');const membership=v.organizations.map(object).find(o=>o.organizationId===organization);if(!membership||!Array.isArray(membership.capabilities)||!membership.capabilities.includes('facility:trip-status:read'))throw new Error('INVALID_FACILITY_SESSION');return {organization,facility};},undefined,signal);},
 day(day:string,after:string|null,signal?:AbortSignal){if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||after!==null&&!uuid.test(after))throw new Error('INVALID_FACILITY_CONTEXT');return transport.request(`${prefix}/days/${day}?limit=100${after?`&after=${after}`:''}`,body=>{const v=object(body);if(Object.keys(v).sort().join()!=='facilityReference,items,nextAfter,serviceDate'||v.facilityReference!==facility||v.serviceDate!==day||!Array.isArray(v.items)||v.items.length>100||v.nextAfter!==null&&(typeof v.nextAfter!=='string'||!uuid.test(v.nextAfter)))throw new Error('INVALID_FACILITY_RESPONSE');const items=v.items.map(decodeFacilityTrip);if(new Set(items.map(t=>t.relatedTripReference)).size!==items.length)throw new Error('DUPLICATE_FACILITY_TRIP');return {items,nextAfter:v.nextAfter as string|null};},undefined,signal);},
 trip(id:string,signal?:AbortSignal){if(!uuid.test(id))throw new Error('INVALID_TRIP_REFERENCE');return transport.request(`${prefix}/trips/${id}`,body=>{const v=decodeFacilityTrip(body);if(v.relatedTripReference!==id)throw new Error('INVALID_FACILITY_RESPONSE');return v;},undefined,signal);}
};}
